config/routes.rb
Rails.application.routes.draw do
  resources :restaurants do
    resources :reviews, only: [ :new, :create ]

  end

  root to: 'restaurants#index'

  namespace :admin do
    resources :restaurants, only: [:edit, :update, :index, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, :dependent => :destroy

  validates :category, inclusion: { in: ["chinese", "italian", "japanese", "french", "belgian"], allow_nil: false }
  validates :name, uniqueness: true, presence: true
  validates :address, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant


  validates :content, presence: true
  validates :rating, presence: true
  validates :rating, numericality: true
  validates :rating, :inclusion => { :in => 0..5 }



end

app/controllers/admin/restaurants_controller.rb
class Admin::RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  def index
    @restaurants = Restaurant.all
  end

  def show
  end

  def destroy
    @restaurant.destroy

    redirect_to admin_restaurants_path
  end

  def update
    @restaurant.update(restaurant_params)

    redirect_to admin_restaurants_path
  end

  def edit
  end

    private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  def index
    @restaurants = Restaurant.all
  end

  def show

  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end

  end

  def edit
  end

  def update
    @restaurant.update(restaurant_params)
    redirect_to restaurants_path
  end

  def destroy
    @restaurant.destroy
    redirect_to restaurants_path
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_restaurant, only: [:new, :create]

  def new

    @review = Review.new
  end

  def create

    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
  end
end

  def show
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/admin/restaurants/edit.html.erb
<h1>Add new restaurant</h1>

<%= simple_form_for @restaurant do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :phone_number %>
  <%= f.input :category, collection: [ "chinese", "italian", "japanese", "french", "belgian"] %>
  <%= f.button :submit %>
<% end %>

app/views/admin/restaurants/index.html.erb
<div class="container">
  <div class="row">
  <h1>Restaurants List</h1>
    <div class="col-xs-12">

      <% @restaurants.each do |restaurant| %>

        <h2><%= link_to restaurant.name, restaurant_path(restaurant) %></h2>
        <p><%= restaurant.address %> </p>
        <p><%= restaurant.phone_number %> </p>
        <p><%= restaurant.category %> </p>

        <%= link_to "Delete", admin_restaurant_path(restaurant),
            method: :delete,
            data: { confirm: "Are you sure?" }, class: "btn btn-primary" %>

                <div>
  <%= link_to "edit", edit_admin_restaurant_path(restaurant), class: "btn btn-primary" %>
</div>

      <% end %>
    </div>
    <div>
</div>



  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
  <div class="navbar-wagon">
  <!-- Logo -->
  <a href="/" class="navbar-wagon-brand">
    <img src="images/logo.png" alt="logo">
  </a>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <a href="" class="navbar-wagon-item navbar-wagon-link">Host</a>
    <a href="" class="navbar-wagon-item navbar-wagon-link">Trips</a>
    <a href="" class="navbar-wagon-item navbar-wagon-link">Messages</a>

    <!-- Profile picture with dropdown list -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <img src="https://kitt.lewagon.com/placeholder/users/ssaunier" class="avatar dropdown-toggle" id="navbar-wagon-menu" data-toggle="dropdown">
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><a href="#">Profile</a></li>
          <li><a href="#">Dashboard</a></li>
          <li><a href="#">Log Out</a></li>
        </ul>
      </div>
    </div>
  </div>

  <!-- Dropdown appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Host</a></li>
        <li><a href="#">Trips</a></li>
        <li><a href="#">Messagese</a></li>
      </ul>
    </div>
  </div>
</div>
    <%= yield %>
  </body>
</html>

app/views/restaurants/create.html.erb
<h1>Restaurants#create</h1>
<p>Find me in app/views/restaurants/create.html.erb</p>

app/views/restaurants/destroy.html.erb
<h1>Restaurants#destroy</h1>
<p>Find me in app/views/restaurants/destroy.html.erb</p>

app/views/restaurants/edit.html.erb
<h1>Restaurants#edit</h1>
<p>Find me in app/views/restaurants/edit.html.erb</p>

app/views/restaurants/index.html.erb
<div class="container">
  <div class="row">
    <h1>Restaurants List</h1>
    <% @restaurants.each do |restaurant| %>
    <div class="col-xs-12 col-sm-4">
      <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('https://kitt.lewagon.com/placeholder/cities/shanghai');">
        <div class="card-category"><%= restaurant.category %></div>
        <div class="card-description">
          <h2> <%= restaurant.name %></h2>
          <p><%= restaurant.address %></p>
          <p><%= restaurant.phone_number %></p>
        </div>
        <img class="card-user" src="https://kitt.lewagon.com/placeholder/users/tgenaitay">
        <%= link_to "", restaurant_path(restaurant) %>
      </div>
    </div>
    <% end %>
    <div>
      <%= link_to "new restaurant", new_restaurant_path, class: "btn btn-primary" %>
    </div>
  </div>
</div>

app/views/restaurants/new.html.erb
<h1>Add new restaurant</h1>

<%= simple_form_for @restaurant do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :phone_number %>
  <%= f.input :category, collection: [ "chinese", "italian", "japanese", "french", "belgian"] %>
  <%= f.button :submit %>
<% end %>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>
<p><%= @restaurant.address %></p>
<p><%= @restaurant.phone_number %></p>
<p><%= @restaurant.category %></p>


<% @restaurant.reviews.each do |review| %>
 <p><%= review.content %></p>
 <p><%= review.rating%></p>

<% end %>

<div>
  <%= link_to "All restaurants", restaurants_path, class: "btn btn-primary" %>
</div>
<div>
  <%= link_to "new review", new_restaurant_review_path(@restaurant), class: "btn btn-success" %>
</div>

app/views/restaurants/update.html.erb
<h1>Restaurants#update</h1>
<p>Find me in app/views/restaurants/update.html.erb</p>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/new.html.erb
<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating, collection: [1,2,3,4,5] %>
  <%= f.submit "add a review", class: "btn btn-primary" %>
<% end %>